spring.application.name=Bankly
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/bankly


spring.datasource.username=${RDB_USERNAME:postgres}
spring.datasource.password=${RDB_PASSWORD:kompjuter1}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
